Cristi/debug lwc tests
forcedotcom/salesforcedx-vscode-automation-tests pull request #76
Opened 2024-05-06 16:47 UTC by CristiCanizales

Implement tests for debugging LWC tests
[W-14866666](https://gus.lightning.force.com/a07EE00001ieHCuYAM)

2024-05-10 13:17 UTC, peternhale requested changes

2024-05-10 13:17 UTC, peternhale commented on test/utilities/sideBar.ts
> +export async function retrieveAllTestItemsFromSidebar(
Good refactor - thanks

2024-05-10 13:17 UTC, peternhale commented on test/utilities/sideBar.ts
>        await refreshAction!.elem.click();
Avoid `!`

2024-05-10 13:17 UTC, peternhale commented on test/utilities/sideBar.ts
> +export async function retrieveAllTestItemsFromSidebar(
One nit, function name `retrieveAllTestItemsFromSidebar` implies that all tests in the section are being fetched, while the implementation will stop the fetch when the number of tests found === expectedNumTests.

Is there a better name for the function?

2024-05-10 14:10 UTC, CristiCanizales commented on test/specs/debugLwcTests.e2e.ts
> +    await browser.keys(['F5']);
This is like clicking the continue button to continue debugging

2024-05-10 14:28 UTC, peternhale commented on test/specs/debugLwcTests.e2e.ts
> +    await browser.keys(['F5']);
Cool, would it make sense for those that follow to use a constant that names what is happening in the UI?

`await browser.keys([CONTINUE]);`

2024-05-10 14:34 UTC, CristiCanizales commented on test/specs/debugLwcTests.e2e.ts
> +    await browser.keys(['F5']);
Sure! Good idea

2024-05-13 12:18 UTC, peternhale approved these changes

2024-05-13 15:09 UTC, merged