chore: fix deploy retrieve tests for esm
forcedotcom/salesforcedx-vscode-automation-tests pull request #93
Opened 2024-07-22 15:16 UTC by peternhale

@W-16285977@

2024-07-22 18:12 UTC, CristiCanizales requested changes
Looks good! Just a couple of questions/comments

[Test run](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10045099446) ✅

2024-07-22 18:12 UTC, CristiCanizales commented on test/utilities/notifications.ts
> +export async function notificationIsAbsent(notificationMessage: string): Promise<boolean> {
this logic+naming is killing me 💀 do we really need this in addition to notificationIsPresent?

2024-07-22 18:12 UTC, CristiCanizales commented on test/utilities/notifications.ts
> +export async function notificationIsAbsentWithTimeout(
same here

2024-07-23 14:06 UTC, peternhale commented on package.json
> +    "@types/fast-levenshtein": "0.0.4",
Going to revert this change

2024-07-23 14:07 UTC, peternhale commented on test/selfSpecs/notifications.test.ts
> +    await expect(isPresent).toBe(false);
The name of the function is misleading. I will fix. Thanks

2024-07-23 14:11 UTC, peternhale commented on test/utilities/miscellaneous.ts
> +    Duration.minutes(10)
This file defines "Duration" so I cannot import it util it is defined.

2024-07-23 16:18 UTC, CristiCanizales approved these changes
Thanks for addressing my comments! Looks good to me! :shipit: 

Test run: [Deploy and Retrieve End to End Tests](https://github.com/forcedotcom/salesforcedx-vscode/actions/runs/10062288068) ✅

2024-07-23 17:22 UTC, merged